service: sam

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: go1.x
  stage: prod
  region: ap-northeast-1

  iamRoleStatements: # permissions for all of your functions can be set here
    - Effect: Allow
      Action: # Gives permission to DynamoDB tables in a specific region
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:ap-northeast-1:*:*"

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  productGet:
    handler: bin/product/get
    events:
      - http:
          path: product
          method: get
  productPut:
    handler: bin/product/put
    events:
      - http:
          path: product
          method: put
  productPost:
      handler: bin/product/post
      events:
        - http:
            path: product
            method: post
  productDelete:
     handler: bin/product/delete
     events:
       - http:
           path: product
           method: delete

resources:
  Resources:
    camera:
      Type: "AWS::DynamoDB::Table"

      Properties:
        AttributeDefinitions:
          -
            AttributeName: "number"
            AttributeType: "S"
        KeySchema:
          -
            AttributeName: "number"
            KeyType: "HASH"

        ProvisionedThroughput:
          ReadCapacityUnits: "1"
          WriteCapacityUnits: "1"
        TableName: "cirgoalAuctionProduct"


